structure_rules:
  base_structure:
    - 'README\.md': required
      # mode: required is default
    - '.*\.md': optional
    - '\.bazelrc'
    - '\.bazelversion'
    - '\.pre-commit-config\.yaml'
    - '[^/]*config\.yaml'
    - "requirements(_lock.txt|.in)"
    - "local_run.sh"
    - "[^/]*.bazel"
    - ".github/"
    - ".github/workflows/"
    - '.github/workflows/[^/]*\.yml'
  python_package:
    - '[^/]*\.py': required
    - "package/": optional
      use_rule: python_package
  software_component:
    - "BUILD"
    - "example/": optional
      if_exists:
        - "example/doc/": required
        - "example/[^/]*": optional

directory_map:
  /:
    - use_rule: base_structure
    - use_rule: python_package
  /test_folder_structure/:
    - use_rule: software_component
