structure_rules:
  base_structure:
    files:
      - name: "README.md"
        mode: required
        # mode: required is default
      - name: '.*\.md'
        mode: optional
      - name: '\.bazelrc'
      - name: '\.bazelversion'
      - name: '\.pre-commit-config\.yaml'
      - name: '[^/]*config\.yaml'
      - name: "requirements(_lock.txt|.in)"
      - name: "local_run.sh"
      - name: "[^/]*.bazel"
    dirs:
      - name: ".github"
        dirs:
          - name: "workflows"
            files:
              - name: '[^/]*\.yml'
  python_package:
    files:
      - name: '[^/]*\.py'
        mode: required
    dirs:
      - name: "package"
        mode: optional
        use_rule: python_package
  software_component:
    files:
      - name: "BUILD"
    dirs:
      - name: "example"
        dirs:
          - name: "doc"
            mode: required
        files:
          - name: "[^/]*"

directory_map:
  /:
    - use_rule: base_structure
    - use_rule: python_package
  /test_folder_structure/:
    - use_rule: software_component
