structure_rules:
  base_structure:
    - p: '\.pre-commit-config\.yaml'
    - p: '[^/]*config\.yaml'
    - p: "environment.yml"
    - p: "local_run.sh"
    - p: 'README\.md'
    - p: "requirements.txt"
    - p: ".github/"
    - p: ".github/workflows/"
    - p: '.github/workflows/[^/]*\.y(a)?ml'
  python_package:
    - p: 'main\.py'
    - p: '[^/]*\.py'

directory_map:
  /:
    - use_rule: base_structure
    - use_rule: python_package
