structure_rules:
  base_structure:
    files:
      - name: "README.md"
        mode: required
        # mode: required is default
      - name: '.*\.md'
        mode: optional
      - name: '\.pre-commit-config\.yaml'
      - name: "[^/]*.yaml"
      - name: "requirements(_lock.txt|.in)"
      - name: '\.bazelversion'
      - name: "[^/]*.sh"
      - name: "[^/]*.bazel"
  python_package:
    files:
      - name: '[^/]*\.py'
        mode: optional
    dirs:
      - name: "[^/]*"
        mode: optional
        use_rule: python_package

directory_mappings:
  /:
    - use_rule: base_structure
    - use_rule: python_package
