structure_rules:
  base_structure:
    - p: 'README\.md'
    - p: '.*\.md'
      required: False
    - p: '\.pre-commit-config\.yaml'
    - p: '[^/]*config\.yaml'
    - p: "requirements.txt"
    - p: "local_run.sh"
    - p: "[^/]*.bazel"
    - p: ".github/"
    - p: ".github/workflows/"
    - p: '.github/workflows/[^/]*\.yml'
  python_package:
    - p: '[^/]*\.py'
    - p: "package/"
      required: False
      use_rule: python_package
  software_component:
    - p: "BUILD"
    - p: "example/"
      required: False
      if_exists:
        - p: "example/doc/"
        - p: "example/[^/]*"
          required: False

directory_map:
  /:
    - use_rule: base_structure
    - use_rule: python_package
  /test_folder_structure/:
    - use_rule: software_component
