structure_rules:
  base_structure:
    files:
      - name: "LICENSE"
        mode: required
      - name: "README.md"
        # mode: required is default
      - name: '.*\.md'
        mode: optional
  python_package:
    dirs:
      - name: "src"
        files:
          - name: '[^/]*\.py'
            mode: optional
            depends: '../test/test_[^/]*\.py'
      - name: "test"
        dirs:
          - name: "data"
            files:
              - name: '[^/]*\.(yaml|yml)'
        files:
          - name: 'test_[^/]*\.py'
      - name: "doc"
        mode: optional
      - name: ".*"
        mode: optional
        use_rule: python_package
    files:
      - name: "setup.py"
        mode: required
  documentation:
    files:
      - name: "index.md"
        mode: required
      - name: '[^/]*\.techspec\.md'
        mode: required
        depends: '[^/]*\.swreq\.md'

directory_mappings:
  /:
    - use_rule: base_structure
    - use_rule: python_package
  /doc/:
    - use_rule: documentation
