structure_rules:
  base_structure:
    required:
      - "LICENSE"
      - "README.md"
    optional:
      - '.*\.md'
  python_package:
    required:
      - "setup.py"
      - "src/":
          - '.*\.py'
      - "tests/":
          - 'test_.*\.py'
          - "data/":
              - '.*\.(yaml|yml)'
    optional:
      - "docs/":
          - use_rule: documentation
      - ".*/":
          - use_rule: python_package
    includes:
      - base_structure
    file_dependencies:
      - implementation_and_test:
          base: '.*\.py'
          dependent: 'test_.*\.py'
      - techspec_and_requirements:
          base: '.*\.techspec\.md'
          dependent: '.*\.swreq\.md'
  documentation:
    required:
      - "index.md"
    optional:
      - '.*\.md'

directory_mappings:
  /:
    - use_rule: python_package
  /docs/:
    - use_rule: documentation
