structure_rules:
  base_structure:
    files:
      - name: "LICENSE"
        mode: required
      - name: "README.md"
        # mode: required is default
      - name: '.*\.md'
        mode: optional
      - name: '\.bazelversion'
      - name: '\.pre-commit-config\.yaml'
  python_package:
    files:
      - name: '[^/]*\.py'
        mode: optional
    dirs:
      - name: "[^/]*"
        mode: optional
        use_rule: python_package
  documentation:
    files:
      - name: "index.md"
        mode: required
      - name: '[^/]*\.techspec\.md'
        mode: required
      - name: '[^/]*\.swreq\.md'

directory_mappings:
  /:
    - use_rule: base_structure
    - use_rule: python_package
  /doc/:
    - use_rule: documentation
