on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
      - name: Install dependencies
        run: |
          conda env create -f environment.yml
          conda init
          conda activate conda_env
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        run: |
          conda activate conda_env
          pytest
